#!/bin/bash

# Usage : <Speaker_Wav_Folder>

SPEAKER_TRAIN_DATA=$1
SPEAKER_TRAIN_MCEP_OUTPUT=$2
SPEAKER_TRAIN_FILES_NAME="Speaker_Speech_Info_File"

FEATURE_EXTRACTION_FOLDER="Feature_Extraction"

#Speaker MCEPS

if [ -d $FEATURE_EXTRACTION_FOLDER/mcep ]; then
	rm -rf $FEATURE_EXTRACTION_FOLDER/mcep
fi

if [ -d $FEATURE_EXTRACTION_FOLDER/wav ]; then
	rm -rf $FEATURE_EXTRACTION_FOLDER/wav
fi
mkdir $FEATURE_EXTRACTION_FOLDER/wav

cp $SPEAKER_TRAIN_DATA/* $FEATURE_EXTRACTION_FOLDER/wav

./get_speech_names.sh $SPEAKER_TRAIN_DATA $FEATURE_EXTRACTION_FOLDER/$SPEAKER_TRAIN_FILES_NAME

cd $FEATURE_EXTRACTION_FOLDER
./run.sh mcep $SPEAKER_TRAIN_FILES_NAME
cd ..

if [ -d $SPEAKER_TRAIN_MCEP_OUTPUT ]; then
	rm -rf $SPEAKER_TRAIN_MCEP_OUTPUT
fi
mkdir $SPEAKER_TRAIN_MCEP_OUTPUT

cp $FEATURE_EXTRACTION_FOLDER/mcep/* $SPEAKER_TRAIN_MCEP_OUTPUT

rm -rf $FEATURE_EXTRACTION_FOLDER/mcep
rm -rf $FEATURE_EXTRACTION_FOLDER/wav
rm -rf $FEATURE_EXTRACTION_FOLDER/$SPEAKER_TRAIN_FILES_NAME

exit 0
