#!/bin/bash

SPEAKER_A_TEST_WAV_DIR=$1
SPEAKER_A_TEST_MCEP_OUTPUT="Speaker_A_Test_MCEPS"
SPEAKER_A_TEST_MCEP_FILE="Speaker_A_Test.mcep"
SPEAKER_A_TEST_F0_FILE="Speaker_A_Test.f0"

SPEAKER_B_WAV_DIR=$2
SPEAKER_B_PREDICED_MCEP_FILE="Speaker_B_Predicted.mcep"
SPEAKER_B_F0_FILE="Speaker_B.f0"
SPEAKER_B_PREDICTED_F0_FILE="Speaker_B_Predicted.f0"
SPEAKER_B_PREDICTED_WAV_FILE="Speaker_B_Predicted.wav"

ANN_FOLDER="ANN_Train_Test"
OUTPUT_MODEL="ANN_Model"

#GET MCEPS
./get_mceps.sh $SPEAKER_A_TEST_WAV_DIR $SPEAKER_A_TEST_MCEP_OUTPUT

#COMBINE MCEPS
./mcep_combine.sh $SPEAKER_A_TEST_MCEP_OUTPUT $SPEAKER_A_TEST_MCEP_FILE

#GET PREDICTED MCEPS
./$ANN_FOLDER/JustTest $ANN_FOLDER/parameters $SPEAKER_A_TEST_MCEP_FILE $SPEAKER_B_PREDICED_MCEP_FILE $OUTPUT_MODEL

#GET SPEAKER B F0
./f0_extract.sh $SPEAKER_B_WAV_DIR
./f0_combine.sh $SPEAKER_B_WAV_DIR.f0 $SPEAKER_B_F0_FILE

#GET SPEAKER A TEST F0
./f0_extract.sh $SPEAKER_A_TEST_WAV_DIR
./f0_combine.sh $SPEAKER_A_TEST_WAV_DIR.f0 $SPEAKER_A_TEST_F0_FILE

#GET PREDICTED B F0
octave --silent --eval "Fcon('$SPEAKER_B_F0_FILE', '$SPEAKER_A_TEST_F0_FILE', '$SPEAKER_B_PREDICTED_F0_FILE')"

#GET WAV
TEMP_MCEP_DIR="Temp_MCEP"
TEMP_F0_DIR="Temp_F0"
TEMP_OUTPUT_DIR="Temp_Output"
mkdir -p $TEMP_MCEP_DIR $TEMP_F0_DIR $TEMP_OUTPUT_DIR

cp $SPEAKER_B_PREDICED_MCEP_FILE $TEMP_MCEP_DIR
cp $SPEAKER_B_PREDICTED_F0_FILE $TEMP_F0_DIR

./synthesize_speechfrom_mceps.sh $TEMP_MCEP_DIR $TEMP_F0_DIR $TEMP_OUTPUT_DIR

cp $TEMP_OUTPUT_DIR/$SPEAKER_B_PREDICTED_WAV_FILE .
rm -rf $TEMP_MCEP_DIR $TEMP_F0_DIR $TEMP_OUTPUT_DIR

exit 0